---
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

env:
  - TOXENV=django110
  - TOXENV=django111

install:
  - pip install -r test-requirements.txt

script:
  - tox

after_success:
  - codecov -e TOXENV,DJANGO
